### ISSUE TITLE
Drift of sensors

### ISSUE THREAD

**Issue by pulledbeef** [ptwz/bedscale#1]
Hey,
I have been working with some force sensor using the hx711.
How does your setup behave with drifting over time?
Because I always have the problem that I have to calibrate the zero point every minute.
Thanks

**Comment by ptwz** [comment]
The software uses only changes in weight. It keeps a ring buffer with the last twenty seconds from the sensors.
Only if the ring buffer's standard deviation (noise, movement) is below 20g the value is considered stable. (i.e. no significant movement/change in weight) for 20 seconds.
Most likely something/somebody will have moved over time, so the scale will register some transitions from stable readings to unstable readings and vice-versa.
Once the system reached a stable state again, lt compares the current weight to the last known stable weight.
Now finally for the drift compensation: If the difference between the last observed stabilized and the current weight is more than 2 kg a datapoint is output. Otherwise the stabilized weight is remembered anyway, so every weight change below two kg will be dismissed an kind of considered drift.

With these 200kg Modules, i observed a creep drift of about 20g/day after a certain settling period of about a week.

Look at lines 45 to 56 in host_process.py for more details as this is quite tricky for me to explain all the subtile things I did to get only good, stable, drift compensated readings.
